apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  imagePullPolicy: Never

  storage:
    size: 1Gi

  #postgresql:
  #  parameters:
  #    pg_stat_statements.max: "10000"
  #    pg_stat_statements.track: all

