apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14.2
  certificates:
    serverCASecret: my-postgresql-server-ca
    serverTLSSecret: my-postgresql-server
    clientCASecret: my-postgresql-server-ca
    replicationTLSSecret: my-postgresql-server

  storage:
    size: 1Gi
  walStorage:
    size: 1Gi

  resources:
    requests:
      memory: "1Gi"
      cpu: "2"
    limits:
      memory: "1Gi"
      cpu: "2"
